name: AWS-Terraform-Test-Exp
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'cicd_misc/*'

jobs:
  terraform-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Install dependencies
        run: make install

      - name: Start LocalStack
        run: make run-localstack

      - name: Terraform Init
        run: make init

      - name: Terraform (Localstack) Apply
        run: make deploy-local

      - name: Lint with pylint
        run: make lint

      - name: Test with pytest
        run: make test
